CREATE TABLE Person
(
    person_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname    varchar(50) NOT NULL,
    name       varchar(50) NOT NULL,
    patronymic varchar(50) NOT NULL,
    yearOfBirt int CHECK (yearOfBirt >= 1930 and yearOfBirt <= 2024),
    UNIQUE (name, surname, patronymic)
);