CREATE TABLE Book
(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   varchar(70) NOT NULL,
    author  varchar(70) NOT NULL,
    year    int CHECK (year <= 2024),
    UNIQUE (author, title, year)
);